### ISSUE TITLE
The title of login page is wrong.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-rs#19]
I found that the title of login page is "S-TIP SNS".
It should be "S-TIP RS" or "S-TIP Repository System".

**Comment by ykoji8681** [comment]
Thanks, @stmtstk .
I think S-TIP login page uses stip-common.
Should we change title string "S-TIP SNS" in stip-common/src/templates/base.html?

```
 <title>{% block title %}S-TIP SNS{% endblock %}</title>
```

**Comment by stmtstk** [comment]
@ykoji8681 correct.
We should replace the title from "S-TIP SNS" to "S-TIP".

**Comment by stmtstk** [comment]
base.html is used from RS, GV, SNS commonly.
so, we should not use a specified application name (like RS, GV, SNS).
So I recommend to use "S-TIP".

**Comment by ykoji8681** [comment]
Thanks. I sent pull request.
https://github.com/s-tip/stip-common/pull/14

**Comment by stmtstk** [comment]
Thanks. I accepted your pr.
