### ISSUE TITLE
Cannot change the language settings in the SNS configuration page

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-rs#45]
The following procedure causes an error.  

1) Login to S-TIP SNS.
2) Click [Account Settings].
3) Select `Portuguese` or `Chinese` in the [Language] field. 
4) Click [Save].

→ `Ensure this value has at most 4 characters (it has 5).` is displayed.

**Comment by stmtstk** [comment]
Thanks @ta-hiroki !!

I checked and approved your code, and merged your working branch into release_11.
You can close this issue.

Thank you again!
