### ISSUE TITLE
Don't delete certificate settings when another setting items are modified and saved.

### ISSUE THREAD

**Issue by tkhsknsk** [s-tip/stip-rs#49]

**Comment by tkhsknsk** [comment]
I checked if it will be reproduced.

Please let me know which one of the two behaviors is the problem.

1. If you register with the same Display Name, it will be overwritten.

2. When the Modify button is pressed, the registered information is displayed on the screen.
The Certificate and Private Key are empty.
If you press the Create or Modify button, it warns you to enter the information and doesn't register.
Do you want to be able to modify other settings without changing the Certificate and Private Key?

-----

再現手順を確認しました。
以下2パターンの挙動があり、どちらが問題なのか教えていただけますか？

1. 同じDisplay Nameで新規登録すると上書きしてしまう。
→ 上書きしますよという警告アラートを出すようにしてほしいのでしょうか？

2. Modifyボタンを押したとき、登録されている情報が画面に表示され、
CertificateとPrivate Keyが空の状態になっています。
そのままCreate or Modifyボタンを押すと情報を入れてって警告が出て登録しない。
→ 上書きされる問題はないが、操作性が下がる。
CertificateとPrivate Keyを変更せずに、他の設定項目を修正できるようにしたいのでしょうか？

**Comment by stmtstk** [comment]
Thank you for your investigation.

When an user overwrite settings with empty Certificate or Private Key, S-TIP should not overwrite them.
When an user would like to modify to unuse an certification authentication, an user set the checkbox unchecked.

----

調査ありがとうございます。

同じ設定名で、  "Modify" をクリックしたとき、

1. Certificate が空なら Certificate を上書きしない
2. Private Key が 空なら PrivateKey を上書きしない
3.そのほかは上書きする
4. もし、ユーザが "User Certificate Authentication" に設定したけど、その設定を取りやめたい時はチェックボックスを外す。その時は、チェックボックスの状態 (False) を書き込み、なおかつ、Certificate, Private Key をempy で上書きする
5. 確認ダイアログは出さなくてもいいのでは。

と、いうのはいかがでしょうか？

**Comment by tkhsknsk** [comment]
If the `Login Password` is also blank, it is not overwritten.
-----
CertificateとPrivate Keyの仕様に合わせて`Login Password`も空でModifyをクリックしたとき
上書きしないように修正します。

**Comment by stmtstk** [comment]
@tkhsknsk 

Nice catch!! It is great.
Thank you!

**Comment by stmtstk** [comment]
@tkhsknsk 

Can I close this issue?
It seems that it is resolved.

**Comment by tkhsknsk** [comment]
@stmtstk
Thank you.
Close this ISSUE.
