### ISSUE TITLE
Add TOTP data fields to mysql.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-rs#63]
Add totp_secret field to stip_common_user.
Set default = None, reqruied = False.

---

stip_common_user に totp_secret field を追加。
設定は default =None, reqruied=Falseとする。

**Comment by ta-hiroki** [comment]
The argument 'reqruied' does not exist, so set 'null=True' instead.

---

reqruied は引数として使えないため代わりに null=True を設定します。

**Comment by ta-hiroki** [comment]
Set 'max_ length=16' because the generated key is 16 characters long.
https://pyotp.readthedocs.io/en/latest/#generating-a-base32-secret-key

---

生成される key は16文字のため max_length=16 を設定。

**Comment by stmtstk** [comment]
@ta-hiroki 

Please set max_length=32 for redundancy。

---

拡張性考えて max_length は 32 にしてもらえませんか？
