### ISSUE TITLE
Show if 2FA is configured on the User list page.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-rs#64]
Add the 2FA field to the User list page ( /confirmation/user/ ) and click the button to display the presence/absence of the 2FA settings for that account.

The button is enabled if totp_secret is not None, disabled if None.

After clicking on the button and confirming with JavaScript, make ajax communicate with totp_secret set to None, indicate success with tostr, and disable the button.

---

User 一覧ページ（ /confugiration/user/ ）に 2FA フィールドを追加し、ボタンでそのアカウントの 2FA の設定の有無を表示する。

このボタンは、totp_secret が None でない場合は有効になり、Noneの場合は無効になります。

ボタンをクリックしてJavaScriptで確認した後、totp_secret を None に設定して ajax を通信させ、tostr で成功を示し、ボタンを無効にします。

**Comment by ta-hiroki** [comment]
@stmtstk 

Is there any problem with the screen image?
(User admin is set to 2FA, so the button is active.)

![image](https://user-images.githubusercontent.com/50686125/89138654-34177b00-d577-11ea-98d5-b73d43e447ee.png)

---

画面のイメージは問題ないでしょうか?
(adminユーザは2FA設定をしているためボタンが活性)

**Comment by stmtstk** [comment]
@ta-hiroki 

Please change below,

- The buttons of 2FA are always enabled.
- When an user does not set 2FA (like na user on the screen short), a text on the button is "Enabled".
- When an user set 2FA already (like admin user on the screen short), a text on the button is "Disabled".

**Comment by ta-hiroki** [comment]
@stmtstk 

> The buttons of 2FA are always enabled.

Is it correct to understand that if 2FA is not set, it is possible to set 2FA on this screen?
(If you are logged in as the admin user, you can configure the 2FA for another user. I think it is better for the admin user to be able to unset the 2FA of other users, but not set it.)

---

2FAが設定されていない場合、この画面で2FAの設定も可能になるという認識でよいでしょうか?
(上記の場合adminユーザでログインしている場合、別ユーザの２FA設定が可能になります。adminユーザは他ユーザの2FAの設定は解除できるが、設定はできない方がよい気がしますがどうでしょうか?)

**Comment by stmtstk** [comment]
@ta-hiroki 

Sorry, I made a mistake.

- The text of 2FA buttons is "unset"
- The unset buttons are enabled if the user set 2FA already.
- The unset buttons are disabled if the user does not set 2FA yet.

---

すみません。間違っていました。

当初通り、下記のようになっていればよいです。
そもそも user setting は admin role しか見られないはずなので。

- ボタンのテキストは "unset"
- 2FA が設定されているユーザは enabed
- 2FA が設定されていないユーザは disabled

ユーザ毎の MFA 設定は別 issue でしたね。

**Comment by ta-hiroki** [comment]
@stmtstk 

> The text of 2FA buttons is "unset"

All right. Modify the button name.

I was concerned about the following process.

- [This process](https://github.com/s-tip/stip-rs/blob/master/src/static/ctirs/js/user_configuration.js#L83) uses toastr() and alert().
Is there any intention?
If there is no particular problem, is it okay to standardize toastr() together with 2FA processing?  

--- 

承知しました。ボタン名変更いたします。

以下、既存処理部で気になりました。
- この辺りの処理は toastr() と alert() が使われています。
使い分けに意図はあるのでしょうか?
特になければ 2FA の処理と合わせて toastr() を利用しても問題ないでしょうか?

**Comment by stmtstk** [comment]
@ta-hiroki 

We should use toastr().
I guessed alert() is used for error and/or debug messages.

**Comment by ta-hiroki** [comment]
@stmtstk 

This is the User screen and the Confirm delete screen.
Please let me know if you have any comments.
- Button name has been set to an appropriate word not 'unset'
- The Confirm screen uses the dialog module

---

User 画面と 削除確認の Confime 画面です。
何かあればコメントください。
- ボタン名は 'unset' でない適切な単語を設定しました
- Confrim 画面は dialog モジュールを使っています

![image](https://user-images.githubusercontent.com/50686125/89363986-71f9d800-d70c-11ea-986e-d1d2b1beea98.png)

![image](https://user-images.githubusercontent.com/50686125/89364209-f2b8d400-d70c-11ea-83ce-b639ebe5f8a5.png)

**Comment by rmasuoka** [comment]
"Disable", not "Disabled", is better for the button. "Disabled" means the status of 2FA being disabled.

**Comment by rmasuoka** [comment]
I also think it is better for the dialog text to be "Disable 2FA". If you say "Disable 2FA settings", it means this lets you to disable the 2FA settings, but not 2FA itself.

**Comment by stmtstk** [comment]
Thanks @rmasuoka .

Please change ...

- The text of buttons. "Disabled" -> "Disable".
- The Dialog Message. "Disable 2FA setting" -> "Disable 2FA".

---

上記の文言で行きましょう。
