### ISSUE TITLE
Modify disable buttons.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-rs#78]
In configuration > user page, 2FA disable buttons are unclear between disabled and enabled.
I would like to put 'Disabled' text instead of disabled buttons when the user does not set 2FA.

---

RS のユーザ設定ページで 2FA の "Disable" ボタンが disabled と enabled の区別がつきにくいです。
そこで、ユーザーが 2FA の設定をしていない場合は "Disable" ボタンを disabled で表示するのではなく、
単に 'Disabled' とテキスト表示するようにしたいです。

**Comment by ta-hiroki** [comment]
@stmtstk 


Please check the screen.

---

画面のイメージです認識あっていますでしょうか?

![image](https://user-images.githubusercontent.com/50686125/90705459-ee281a00-e2cd-11ea-9341-ba4ff4806f33.png)

**Comment by stmtstk** [comment]
@ta-hiroki 

OK.
