### ISSUE TITLE
It failed to import/export from/to MISP instance.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-rs#8]
We set up MISP instance on AWS with self-signed certification.
And, we set MISP host and API key on MISP adapter.
After setting, we tried to import MISP event, but it failed.
It seems to occur a communication error because of using self-singed certification.

**Comment by stmtstk** [comment]
I also add a STIX Package ID prefix setting instead of MISP domain name in MISP adapter page.

**Comment by stmtstk** [comment]
We have to install "misp_stix_converter".

pip install  misp_stix_converter

**Comment by ykoji8681** [comment]
I added misp_stix_converter to requirements.txt.
