### ISSUE TITLE
Add tag search criteria.

### ISSUE THREAD

**Issue by ta-hiroki** [s-tip/stip-rs#97]
When a tag (Words beginning with #) is searched on STIP-SNS, it is searched by an exact match.
This is the issue related to https://github.com/s-tip/stip-sns/issues/86.

---

STIP-SNS でタグ（#で始まる単語）が検索された場合、完全一致で検索する。

**Comment by ta-hiroki** [comment]
@stmtstk 

I don’t know what to do.
The current search function gets from the fields defined in the StixFiles class.
However, the StixFiles class does not have tag information.
Therefore, I am wondering how to search by tag information.

---

私はデータの取得方法で悩んでいます。
今の検索機能はStixFilesクラスで定義されたフィールドから取得している。
しかし、StixFilesクラスではタグ情報を持っていない。
そのためどのように tag 情報で検索するのが良いか悩んでいる。

**Comment by stmtstk** [comment]
I recommend to add a new tags field (List of String) into `STIXFiles` Collcetion.
When `stip-rs` registers a STIX 2.x file, it also stores tags into STIX files same time.
On query STIX Files, add query like `Q(tags__in=='a_search_word')

---
1. (stip-rs の) mongo document STIXFiles に tags Field を追加する (string の List) を追加する
2. https://github.com/s-tip/stip-rs/blob/2193effa352ff25135ec9dba33f19bfed1133471/src/ctirs/core/mongo/documents_stix.py#L305

ここの self は STIXFiles なので、 labels の内容を tags に代入して保存する

3. https://github.com/s-tip/stip-rs/blob/master/src/ctirs/api/v1/sns/views.py
query ルールに Q(tags__in='検索文字') を入れる

でどうでしょうか？

**Comment by ta-hiroki** [comment]
@stmtstk 

I want to use [is_tag()](https://github.com/s-tip/stip-sns/pull/98/files#diff-a1f9c0b74d90d0bf9ca89f6d6a8eea5b0d4bae23a26c1ec3fe33a5328fcbc31dR1652) function in rs repository.
It currently exists in the sns repository, but I think it's better to move it to the common repository. What do you think?
(If there is no problem, I will deal with it.)

---

[タグか判断する関数](https://github.com/s-tip/stip-sns/pull/98/files#diff-a1f9c0b74d90d0bf9ca89f6d6a8eea5b0d4bae23a26c1ec3fe33a5328fcbc31dR1652)を rs リポジトリ の src でも利用したいです。
今は sns リポジトリに存在しますが、
common リポジトリに配置した方がよいと思いますがどうでしょうか?
(問題がなければ対応いたします)

**Comment by stmtstk** [comment]
@ta-hiroki 

We should create a new file `tag.py` in [src/stip/common](https://github.com/s-tip/stip-common/tree/master/src/stip/common) and move `is_tag()` to tag.py.

---

`is_tag()` は common に移しましょう。上記 URL の中に `tag.py` を作って、そこに移動させましょう。

**Comment by stmtstk** [comment]
I'm wondering whether S-TIP should judge to hit a tag word in a title, screen_name ,and user_name.
Please wait.

---

タイトル、ユーザースクリーン名、ユーザ名に検索フィールドのタグ文字列が含まれたときに、
マッチすべきかどうか迷っています。
ちょっと仕様を考えます。少々お待ちください。

現状の動作の以下は動作を確認しています。

- 検索フィールドタグが 2 つ以上あるときは and 検索 (今までと同様)
- 検索フィールドがタグの時は post の内容だけチェックして、検索タグの完全一致が含まれた時のみ抽出
