### ISSUE TITLE
Add a tags filed in the Feed class.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-rs#98]
For post with tag links, we shoud add `post_org` in the Feed class.
The type of `post_org` is same as `post` field.

S-TIP stores a user post added tag links into `post`.
S-TIP also strores original post into `post_org` field instead of `post` field.

---

Feed を表示するたびに post の内容から Tags を抽出して、post に対してリンクを付与している処理を行っています。
しかしながら、post の内容は変わらないのでこの処理は冗長です。
したがって、最初の post 解析時に link を付けた文字列を `post` フィールドに保存する処理を行います。

オリジナルの post の文字列も保存すべきで、そのためにこの Issue では `post_org` フィールドを追加します。
型は `post` と同じにしましょう。

**Comment by ta-hiroki** [comment]
@stmtstk 

Is the default value '' OK?
(The recognition that a default setting is required for a field that does not exist in an existing record.)

**Comment by stmtstk** [comment]
@ta-hiroki 

Yes.
I think it is nice idea to set an empty string as a default value.
